apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hpc-workload-generator-storage
  namespace: uky-hpc-workload-generator
spec:
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
