apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hpc-workload-generator-storage
  namespace: uky-hpc-workload-generator
spec:
  storageClassName: ocs-storagecluster-cephfs
  volumeName: pvc-eafc2cc6-da07-48c9-bd45-b747581f032f
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
