apiVersion: v1
kind: Pod
metadata:
  name: hpc-workload-generator
  labels:
    app: hpc-workload-generator
  namespace: uky-hpc-workload-generator
spec:
  restartPolicy: OnFailure
  serviceAccountName: hpc-workload-generator
  volumes:
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
    - name: hpc-workload-generator-storage
      persistentVolumeClaim:
        claimName: hpc-workload-generator-storage
  initContainers:
    - name: prepare-storage
      image: busybox
      command:
        - "/bin/sh"
        - "-c"
      args:
        - >-
          rm -rf /data/* &&
          echo "0, cpuload, 0, 10, 30" >> /data/schedule &&
          echo "0, cpuload, 1, 100, 30" >> /data/schedule &&
          echo "30, cpuload, 0, 20, 30" >> /data/schedule &&
          echo "30, cpuload, 1, 90, 30" >> /data/schedule &&
          echo "60, cpuload, 0, 30, 30" >> /data/schedule &&
          echo "60, cpuload, 1, 80, 30" >> /data/schedule &&
          echo "90, cpuload, 0, 40, 30" >> /data/schedule &&
          echo "90, cpuload, 1, 70, 30" >> /data/schedule &&
          echo "120, cpuload, 0, 50, 30" >> /data/schedule &&
          echo "120, cpuload, 1, 60, 30" >> /data/schedule &&
          echo "150, cpuload, 0, 60, 30" >> /data/schedule &&
          echo "150, cpuload, 1, 50, 30" >> /data/schedule &&
          echo "180, cpuload, 0, 70, 30" >> /data/schedule &&
          echo "180, cpuload, 1, 40, 30" >> /data/schedule &&
          echo "210, cpuload, 0, 80, 30" >> /data/schedule &&
          echo "210, cpuload, 1, 30, 30" >> /data/schedule &&
          echo "240, cpuload, 0, 90, 30" >> /data/schedule &&
          echo "240, cpuload, 1, 20, 30" >> /data/schedule &&
          echo "270, cpuload, 0, 100, 30" >> /data/schedule &&
          echo "270, cpuload, 1, 10, 30" >> /data/schedule
      volumeMounts:
        - name: hpc-workload-generator-storage
          mountPath: /data
  containers:
    - name: hpc-workload-generator
      image: phphavok/hpc-workload-generator
      command:
        - "bash"
        - "-c"
      args:
        - >-
          cp -f /proc/$$$$/cgroup /data/cgroup.spec &&
          ./hpc-workload-generator -i /data/schedule &&
          sleep 600
      volumeMounts:
        - name: cgroup
          mountPath: /sys/fs/cgroup
        - name: hpc-workload-generator-storage
          mountPath: /data
      resources:
        requests:
          cpu: "4"
          memory: "1Gi"
        limits:
          cpu: "4"
          memory: "1Gi"
    - name: cgroups-exporter
      image: phphavok/cgroups_exporter
      args:
        - "-method"
        - "file"
        - "-file"
        - "/data/cgroup.spec"
      volumeMounts:
        - name: cgroup
          mountPath: /sys/fs/cgroup
        - name: hpc-workload-generator-storage
          mountPath: /data
